services:
  csharp-highlighter:
    image: csharp-highlighter
    build:
      context: ../../../
      dockerfile: src/services/CsharpHighlighter/Dockerfile
    ports:
      - "6002:8080"
    environment:
      - OTLP_Receiver_Endpoint=otel-collector:4317
    networks:
      highlighter-network:
    hostname: csharp-highlighter
      


networks:
  highlighter-network:
    name: highlighter-network
    external: true
    driver: bridge
