services:
  fortranhighlighter:
    image: fortranhighlighter
    build:
      context: .
      dockerfile: FortranHighlighter/Dockerfile

  fortranhighlighter-1:
    image: fortranhighlighter-1
    build:
      context: .
      dockerfile: src/FortranHighlighter/Dockerfile

