services:
  clojurehighlighter:
    image: clojurehighlighter
    build:
      context: ../../../
      dockerfile: src/services/ClojureHighlighter/Dockerfile
    hostname: clojure-highlighter
    networks:
      highlighter-network:
    ports:
      - "6000:8080"
    environment:
      - OTLP_Receiver_Endpoint=http://otel-collector:4317


networks:
  highlighter-network:
    name: highlighter-network
    external: true
    driver: bridge
