services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    hostname: otel-collector
    volumes:
      - ./configs/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317" #Grpc 
      - "4318:4318" #Http
      - "8889:8889"
    networks:
      - highlighter-network
  
  
  loki:
    image: grafana/loki:latest
    container_name: loki
    command: [ "-config.file=/etc/loki/local-config.yaml" ]
    ports:
      - "3100:3100"
    user: "0:0"
    volumes:
      - ./configs/loki-config.yaml:/etc/loki/local-config.yaml
      - ./data/loki-data:/loki
    networks:
      - highlighter-network


  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./configs/tempo.yaml:/etc/tempo.yaml
      - ./data/tempo-data:/tmp/tempo
    ports:
      - "3200:3200"
      - "7946:7946"  # Add memberlist port
    networks:
      - highlighter-network
    user: "0:0"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    volumes:
      - ./configs/prometheus.yaml:/etc/prometheus/prometheus.yml
      - ./data/prometheus-data:/prometheus
    ports:
      - "9090:9090"
    user: "0:0"
    networks:
      - highlighter-network


  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./configs/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yml
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - highlighter-network
    depends_on:
      - loki
      - tempo
      - prometheus


networks:
  highlighter-network:
    name: highlighter-network
    driver: bridge

volumes:
  loki-data:
  tempo-data:
  prometheus-data:
  grafana-data: