services:
  fortranhighlighter:
    image: fortranhighlighter
    build:
      context: ../../../
      dockerfile: src/services/FortranHighlighter/Dockerfile
    ports:
      - "7000:8080"
    environment:
      - OTLP_Receiver_Endpoint=http://otel-collector:4317
    hostname: fortran-highlighter
    networks:
      highlighter-network:
      




networks:
  highlighter-network:
    name: highlighter-network
    external: true
    driver: bridge