services:
  fortranhighlighter:
    image: fortranhighlighter
    build:
      context: .
      dockerfile: src/services/FortranHighlighter/Dockerfile
    ports:
      - "6001:6001"
    environment:
      - OTLP_Receiver_Endpoint=otel-collector:4317
    hostname: fortran-highlighter
    networks:
      highlighter-network:
      




networks:
  highlighter-network:
    name: highlighter-network
    driver: bridge
